language: python
python:
  - "2.7"
env:
  - TOXENV=py26-1.6.X,py27-1.6.X
  - TOXENV=py27-1.7.X
  - TOXENV=py27-trunk
  - TOXENV=docs
  - TOXENV=flake8
  - TOXENV=coverage
install:
  - pip install --upgrade tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
