language: python
python:
  - "2.7"
env:
  - TOXENV=py26-1.4.X,py27-1.4.X
  - TOXENV=py26-1.5.X,py27-1.5.X
  - TOXENV=py26-1.6.X,py27-1.6.X
  - TOXENV=py27-1.7.X
  - TOXENV=py27-trunk
  - TOXENV=docs
  - TOXENV=flake8
  - TOXENV=coverage
install:
  - pip install tox
script:
  - tox
matrix:
  allow_failures:
    - env: TOXENV=py27-1.7.X
    - env: TOXENV=py27-trunk
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
