language: python
dist: trusty
sudo: false
python:
  - "2.7"
install:
  - pip install --upgrade tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
matrix:
  allow_failures:
    - env: TOXENV=py27-trunk
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
